apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: ts-grpc
  namespace: kserve-demo
  annotations:
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
    route.openshift.io/termination: "edge"
spec:
  predictor:
    triton:
      storageUri: gs://kfserving-examples/models/torchscript
      runtimeVersion: 20.10-py3
      ports:
        - containerPort: 9000
          name: h2c
          protocol: TCP
      env:
        - name: OMP_NUM_THREADS
          value: "1"
